version: '{build}'
image:
  - Visual Studio 2015
  - Ubuntu
build_script:
  - ./mvnw clean package -DskipTests
test_script:
  - ./mvnw clean verify
after_test:
  - sh: CODECOV_TOKEN="78462305-d76b-4bf7-8f31-4f152ed61c02" bash <(curl -s https://codecov.io/bash)
