version: '{build}'
image:
  - Visual Studio 2015
  - Ubuntu
stack: jdk 8
cache:
  - /home/appveyor/.m2
  - C:\Users\appveyor\.m2
build_script:
  - ./mvnw clean package -DskipTests
test_script:
  - ./mvnw clean verify
after_test:
  - sh: CODECOV_TOKEN="be37aef1-3b14-4433-9d91-c8dd3af65285" bash <(curl -s https://codecov.io/bash)
